#ifndef CODE_TESTCASES_H
#define CODE_TESTCASES_H
int test1();
int test2();
int test_svc_rm1();
int test_print_commit_3();
int test_svc_checkout1();
int get_prev_commits3();
#endif //CODE_TESTCASES_H
